version: "3.8"

services:
  web:
    image: bunkerity/bunkerweb:1.5.6
    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE=yes"
    volumes:
      - ./bw-data:/data
    env_file:
      - .env_web
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.6
    depends_on:
      - web
      - bw-docker
    volumes:
      - ./bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

  odoo:
    image: odoo:17.0
    depends_on:
      - postgres
      - web
    volumes:
      - ./odoo/data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
    env_file:
      - .env_odoo
    networks:
      - bw-services

  postgres:
    image: postgres:15
    volumes:
      - ./db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env_postgres
    networks:
      - bw-services
  
networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
