version: '3'

services:

  web:
    image: bunkerity/bunkerweb:1.5.6
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./bw-data:/data
    env_file:
      - .env_web

  odoo:
    image: odoo:17.0
    depends_on:
      - postgres
      - web
    volumes:
      - ./odoo/data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
    env_file:
      - .env_odoo
  
  postgres:
    image: postgres:15
    volumes:
      - ./db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env_postgres
